// <auto-generated />
using System;
using MateriasPrimasApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MateriasPrimasApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("MateriasPrimaApp.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Categoria");

                    b.HasData(
                        new { Id = 1, Descripcion = "Metales ferrosos tales como Hierro y Acero", Nombre = "Ferroso" },
                        new { Id = 2, Descripcion = "Metales no ferrosos tales como Aluminio y Cobre", Nombre = "No Ferroso" },
                        new { Id = 3, Descripcion = "Envases de cristal como Botellas de cerveza y otros productos reciclables como el cartón", Nombre = "Envases y varios" }
                    );
                });

            modelBuilder.Entity("MateriasPrimaApp.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Codigo")
                        .IsRequired();

                    b.Property<string>("Nombre")
                        .IsRequired();

                    b.Property<string>("Organismo");

                    b.HasKey("Id");

                    b.ToTable("Cliente");

                    b.HasData(
                        new { Id = 1, Codigo = "C001", Nombre = "CTEAG", Organismo = "UNE" }
                    );
                });

            modelBuilder.Entity("MateriasPrimaApp.Models.DetalleDeEntrada", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("Cantidad");

                    b.Property<int>("EntradaId");

                    b.Property<decimal>("PrecioMlc")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("PrecioMn")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("ProductoId");

                    b.HasKey("Id");

                    b.HasIndex("EntradaId");

                    b.HasIndex("ProductoId");

                    b.ToTable("DetallesDeEntradas");
                });

            modelBuilder.Entity("MateriasPrimaApp.Models.DetalleDeTraslado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("Cantidad");

                    b.Property<decimal>("PrecioMlc")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("PrecioMn")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("ProductoId");

                    b.Property<int>("TrasladoId");

                    b.HasKey("Id");

                    b.HasIndex("ProductoId");

                    b.HasIndex("TrasladoId");

                    b.ToTable("DetallesDeTraslado");
                });

            modelBuilder.Entity("MateriasPrimaApp.Models.Entrada", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ClienteId");

                    b.Property<bool>("Confirmada");

                    b.Property<DateTime>("Fecha");

                    b.Property<int>("UnidadOrganizativaId");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("UnidadOrganizativaId");

                    b.ToTable("Entrada");
                });

            modelBuilder.Entity("MateriasPrimaApp.Models.Procesamiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("CantidadOrigen");

                    b.Property<decimal>("CantidadSalida");

                    b.Property<bool>("Confirmada");

                    b.Property<int>("ProductoOrigenId");

                    b.Property<int>("ProductoSalidaId");

                    b.HasKey("Id");

                    b.HasIndex("ProductoOrigenId");

                    b.HasIndex("ProductoSalidaId");

                    b.ToTable("Procesamientos");
                });

            modelBuilder.Entity("MateriasPrimaApp.Models.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CategoriaId");

                    b.Property<string>("Codigo")
                        .IsRequired();

                    b.Property<string>("Descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired();

                    b.Property<decimal>("PrecioCompraMlc")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("PrecioCompraMn")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("PrecioVentaMlc")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("PrecioVentaMn")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("TipoId");

                    b.Property<int>("UnidadId");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("TipoId");

                    b.HasIndex("UnidadId");

                    b.ToTable("Producto");

                    b.HasData(
                        new { Id = 1, CategoriaId = 1, Codigo = "1abcc345", Descripcion = "Hierro Fundido", Nombre = "Hierro", PrecioCompraMlc = 4m, PrecioCompraMn = 100m, PrecioVentaMlc = 0m, PrecioVentaMn = 0m, TipoId = 1, UnidadId = 1 },
                        new { Id = 2, CategoriaId = 3, Codigo = "2def678", Descripcion = "Botella de Ron", Nombre = "Botella de Ron", PrecioCompraMlc = 0.05m, PrecioCompraMn = 1m, PrecioVentaMlc = 0m, PrecioVentaMn = 0m, TipoId = 2, UnidadId = 3 }
                    );
                });

            modelBuilder.Entity("MateriasPrimaApp.Models.Submayor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AlmacenId");

                    b.Property<decimal>("Cantidad");

                    b.Property<int>("ProductoId");

                    b.Property<int>("UnidadId");

                    b.HasKey("Id");

                    b.HasIndex("AlmacenId");

                    b.HasIndex("ProductoId");

                    b.HasIndex("UnidadId");

                    b.ToTable("Submayor");

                    b.HasData(
                        new { Id = 1, AlmacenId = 1, Cantidad = 1300m, ProductoId = 1, UnidadId = 1 }
                    );
                });

            modelBuilder.Entity("MateriasPrimaApp.Models.TipoDeProducto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("TipoDeProducto");

                    b.HasData(
                        new { Id = 1, Descripcion = "Metales", Nombre = "Metálico" },
                        new { Id = 2, Descripcion = "Otros Materiales no metálicos", Nombre = "No Metálico" }
                    );
                });

            modelBuilder.Entity("MateriasPrimaApp.Models.Traslado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ClienteId");

                    b.Property<bool>("Confirmada");

                    b.Property<int>("DestinoId");

                    b.Property<DateTime>("Fecha");

                    b.Property<int>("OrigenId");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("DestinoId");

                    b.HasIndex("OrigenId");

                    b.ToTable("Traslado");
                });

            modelBuilder.Entity("MateriasPrimaApp.Models.UnidadDeMedida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Descripcion");

                    b.Property<string>("Unidad")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("UM");

                    b.HasData(
                        new { Id = 1, Descripcion = "Tonelada", Unidad = "Ton" },
                        new { Id = 2, Descripcion = "KiloGramo", Unidad = "Kg" },
                        new { Id = 3, Descripcion = "Unidad", Unidad = "U" }
                    );
                });

            modelBuilder.Entity("MateriasPrimaApp.Models.UnidadOrganizativa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<string>("Nombre")
                        .IsRequired();

                    b.Property<string>("Telefono");

                    b.HasKey("Id");

                    b.ToTable("UnidadOrganizativa");

                    b.HasDiscriminator<string>("Discriminator").HasValue("UnidadOrganizativa");
                });

            modelBuilder.Entity("MateriasPrimaApp.Models.Venta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ClienteId");

                    b.Property<bool>("Confirmada");

                    b.Property<DateTime>("Fecha");

                    b.Property<int>("UnidadOrganizativaId");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("UnidadOrganizativaId");

                    b.ToTable("Venta");
                });

            modelBuilder.Entity("MateriasPrimasApp.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<bool>("Active");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<int?>("UnidadOrganizativaId");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex");

                    b.HasIndex("UnidadOrganizativaId");

                    b.ToTable("AspNetUsers");

                    b.HasData(
                        new { Id = "f42559a2-2776-4e9b-9ba1-268597eff72b", AccessFailedCount = 0, Active = true, ConcurrencyStamp = "36fd2616-8e8a-4cc6-8a5a-52d963207836", Email = "admin@materiaprima.cu", EmailConfirmed = false, LockoutEnabled = false, NormalizedEmail = "ADMIN@MATERIAPRIMA.CU", NormalizedUserName = "ADMIN", PasswordHash = "AQAAAAEAACcQAAAAEP4OedI6m26WUn/2C4AcBkzdT6SnL/6E+xakQ/9mGAkqqp3t9PwyIR6l9obLouKIVg==", PhoneNumberConfirmed = false, SecurityStamp = "43VMKYQKNTENYZVJNU2TII26X23H5PGV", TwoFactorEnabled = false, UserName = "admin" },
                        new { Id = "e4acfaab-e3c9-42ef-9e21-1902da5374af", AccessFailedCount = 0, Active = true, ConcurrencyStamp = "e3730b4c-284a-48da-ace3-b5f31f5671df", Email = "user1@mp.cu", EmailConfirmed = false, LockoutEnabled = false, NormalizedEmail = "USER1@MP.CU", NormalizedUserName = "USER1", PasswordHash = "AQAAAAEAACcQAAAAECmA0XlVxV7cpw5UFHBIIDAKwZ9RSjLf0g5QOiC9UwYIi8cn0Lw+2QqwOsDdtWkEyw==", PhoneNumberConfirmed = false, SecurityStamp = "4AVYZFGP54QSAT3RJN4KI5R327NN4ID2", TwoFactorEnabled = false, UnidadOrganizativaId = 1, UserName = "user1" }
                    );
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex");

                    b.ToTable("AspNetRoles");

                    b.HasData(
                        new { Id = "1", ConcurrencyStamp = "52307b38-f8fb-4b4b-87b9-18b71be7d636", Name = "Administrador", NormalizedName = "ADMINISTRADOR" },
                        new { Id = "2", ConcurrencyStamp = "054af328-99f0-458a-a3d0-9bf57f5b232e", Name = "Usuario", NormalizedName = "USUARIO" }
                    );
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("RoleId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider");

                    b.Property<string>("ProviderKey");

                    b.Property<string>("ProviderDisplayName");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");

                    b.HasData(
                        new { UserId = "f42559a2-2776-4e9b-9ba1-268597eff72b", RoleId = "1" },
                        new { UserId = "e4acfaab-e3c9-42ef-9e21-1902da5374af", RoleId = "2" }
                    );
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("LoginProvider");

                    b.Property<string>("Name");

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("MateriasPrimaApp.Models.CasaCompra", b =>
                {
                    b.HasBaseType("MateriasPrimaApp.Models.UnidadOrganizativa");

                    b.Property<int>("UebId");

                    b.HasIndex("UebId");

                    b.ToTable("CasaCompra");

                    b.HasDiscriminator().HasValue("CasaCompra");

                    b.HasData(
                        new { Id = 3, Nombre = "Casa de compras Versalles", UebId = 1 },
                        new { Id = 4, Nombre = "Casa de compras Playa", UebId = 1 }
                    );
                });

            modelBuilder.Entity("MateriasPrimaApp.Models.UEB", b =>
                {
                    b.HasBaseType("MateriasPrimaApp.Models.UnidadOrganizativa");

                    b.Property<string>("Municipio");

                    b.ToTable("UEB");

                    b.HasDiscriminator().HasValue("UEB");

                    b.HasData(
                        new { Id = 1, Nombre = "UEBMtz", Telefono = "262100", Municipio = "Matanzas" },
                        new { Id = 2, Nombre = "UEBCol", Telefono = "371304", Municipio = "Colón" }
                    );
                });

            modelBuilder.Entity("MateriasPrimaApp.Models.DetalleDeEntrada", b =>
                {
                    b.HasOne("MateriasPrimaApp.Models.Entrada", "Entrada")
                        .WithMany()
                        .HasForeignKey("EntradaId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MateriasPrimaApp.Models.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MateriasPrimaApp.Models.DetalleDeTraslado", b =>
                {
                    b.HasOne("MateriasPrimaApp.Models.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MateriasPrimaApp.Models.Traslado", "Traslado")
                        .WithMany()
                        .HasForeignKey("TrasladoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MateriasPrimaApp.Models.Entrada", b =>
                {
                    b.HasOne("MateriasPrimaApp.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MateriasPrimaApp.Models.UnidadOrganizativa", "UnidadOrganizativa")
                        .WithMany()
                        .HasForeignKey("UnidadOrganizativaId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MateriasPrimaApp.Models.Procesamiento", b =>
                {
                    b.HasOne("MateriasPrimaApp.Models.Producto", "ProductoOrigen")
                        .WithMany()
                        .HasForeignKey("ProductoOrigenId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MateriasPrimaApp.Models.Producto", "ProductoSalida")
                        .WithMany()
                        .HasForeignKey("ProductoSalidaId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MateriasPrimaApp.Models.Producto", b =>
                {
                    b.HasOne("MateriasPrimaApp.Models.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MateriasPrimaApp.Models.TipoDeProducto", "Tipo")
                        .WithMany()
                        .HasForeignKey("TipoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MateriasPrimaApp.Models.UnidadDeMedida", "Unidad")
                        .WithMany()
                        .HasForeignKey("UnidadId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MateriasPrimaApp.Models.Submayor", b =>
                {
                    b.HasOne("MateriasPrimaApp.Models.UnidadOrganizativa", "Almacen")
                        .WithMany()
                        .HasForeignKey("AlmacenId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MateriasPrimaApp.Models.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MateriasPrimaApp.Models.UnidadDeMedida", "Unidad")
                        .WithMany()
                        .HasForeignKey("UnidadId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MateriasPrimaApp.Models.Traslado", b =>
                {
                    b.HasOne("MateriasPrimaApp.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MateriasPrimaApp.Models.UnidadOrganizativa", "Destino")
                        .WithMany()
                        .HasForeignKey("DestinoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MateriasPrimaApp.Models.UnidadOrganizativa", "Origen")
                        .WithMany()
                        .HasForeignKey("OrigenId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MateriasPrimaApp.Models.Venta", b =>
                {
                    b.HasOne("MateriasPrimaApp.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MateriasPrimaApp.Models.UnidadOrganizativa", "UnidadOrganizativa")
                        .WithMany()
                        .HasForeignKey("UnidadOrganizativaId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MateriasPrimasApp.Models.ApplicationUser", b =>
                {
                    b.HasOne("MateriasPrimaApp.Models.UnidadOrganizativa", "UnidadOrganizativa")
                        .WithMany()
                        .HasForeignKey("UnidadOrganizativaId");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("MateriasPrimasApp.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("MateriasPrimasApp.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MateriasPrimasApp.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("MateriasPrimasApp.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MateriasPrimaApp.Models.CasaCompra", b =>
                {
                    b.HasOne("MateriasPrimaApp.Models.UEB", "Ueb")
                        .WithMany()
                        .HasForeignKey("UebId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
